declare module 'lucide-react' {
  import * as React from 'react';
  export interface LucideProps extends React.SVGProps<SVGSVGElement> {
    size?: number | string;
    color?: string;
    strokeWidth?: number | string;
    absoluteStrokeWidth?: boolean;
  }
  export type LucideIcon = React.FC<LucideProps>;
  const Icon: LucideIcon;
  export default Icon;

  // — Toutes les icônes lucide utilisées dans le projet —
  export const AlertCircle: LucideIcon;
  export const AlertTriangle: LucideIcon;
  export const ArrowDown: LucideIcon;
  export const ArrowLeft: LucideIcon;
  export const ArrowRight: LucideIcon;
  export const ArrowUp: LucideIcon;
  export const BarChart3: LucideIcon;
  export const BookOpen: LucideIcon;
  export const Calculator: LucideIcon;
  export const Calendar: LucideIcon;
  export const Camera: LucideIcon;
  export const Check: LucideIcon;
  export const CheckCircle2: LucideIcon;
  export const ChevronDown: LucideIcon;
  export const ChevronLeft: LucideIcon;
  export const ChevronRight: LucideIcon;
  export const Clock: LucideIcon;
  export const Copy: LucideIcon;
  export const CreditCard: LucideIcon;
  export const Download: LucideIcon;
  export const ExternalLink: LucideIcon;
  export const Eye: LucideIcon;
  export const EyeOff: LucideIcon;
  export const Facebook: LucideIcon;
  export const FileText: LucideIcon;
  export const FileWarning: LucideIcon;
  export const GalleryHorizontalEnd: LucideIcon;
  export const Globe: LucideIcon;
  export const HandHeart: LucideIcon;
  export const Handshake: LucideIcon;
  export const Heart: LucideIcon;
  export const Home: LucideIcon;
  export const Image: LucideIcon;
  export const ImageIcon: LucideIcon;
  export const Info: LucideIcon;
  export const Instagram: LucideIcon;
  export const KeyRound: LucideIcon;
  export const Languages: LucideIcon;
  export const Layers: LucideIcon;
  export const LayoutDashboard: LucideIcon;
  export const Library: LucideIcon;
  export const Link2: LucideIcon;
  export const Loader2: LucideIcon;
  export const LogOut: LucideIcon;
  export const Mail: LucideIcon;
  export const MapPin: LucideIcon;
  export const Menu: LucideIcon;
  export const MessageCircle: LucideIcon;
  export const MessageSquare: LucideIcon;
  export const Minus: LucideIcon;
  export const Moon: LucideIcon;
  export const Music: LucideIcon;
  export const Package: LucideIcon;
  export const Pause: LucideIcon;
  export const Pencil: LucideIcon;
  export const PhoneCall: LucideIcon;
  export const Play: LucideIcon;
  export const Plus: LucideIcon;
  export const Printer: LucideIcon;
  export const Save: LucideIcon;
  export const ScanFace: LucideIcon;
  export const Search: LucideIcon;
  export const Send: LucideIcon;
  export const Settings: LucideIcon;
  export const Share2: LucideIcon;
  export const ShieldAlert: LucideIcon;
  export const ShieldCheck: LucideIcon;
  export const ShoppingBag: LucideIcon;
  export const ShoppingCart: LucideIcon;
  export const Sparkle: LucideIcon;
  export const Sparkles: LucideIcon;
  export const Sun: LucideIcon;
  export const Tag: LucideIcon;
  export const Trash2: LucideIcon;
  export const Trophy: LucideIcon;
  export const Truck: LucideIcon;
  export const Hash: LucideIcon;
  export const TrendingUp: LucideIcon;
  export const Slack: LucideIcon;
  export const Webhook: LucideIcon;
  export const Bot: LucideIcon;
  export const Github: LucideIcon;
  export const Cloud: LucideIcon;
  export const Zap: LucideIcon;
  export const Database: LucideIcon;
  export const Power: LucideIcon;
  export const PowerOff: LucideIcon;
  export const Layers: LucideIcon;
  export const Sun: LucideIcon;
  export const Moon: LucideIcon;
  export const Search: LucideIcon;
  export const MessageSquare: LucideIcon;
  export const ShoppingCart: LucideIcon;
  export const HandHeart: LucideIcon;
  export const Twitter: LucideIcon;
  export const Type: LucideIcon;
  export const UploadCloud: LucideIcon;
  export const Users: LucideIcon;
  export const Video: LucideIcon;
  export const Volume2: LucideIcon;
  export const VolumeX: LucideIcon;
  export const Wand2: LucideIcon;
  export const X: LucideIcon;
  export const Youtube: LucideIcon;

  // Catch-all
  export const ALL_ICONS: { [k: string]: LucideIcon };
}
